// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://mezwwjzchbvfpptljmya.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lend3anpjaGJ2ZnBwdGxqbXlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NjE0NDcsImV4cCI6MjA2ODIzNzQ0N30.lB4HBcu2Gnsx03ozkEjZLfWkkVW_hgWxwdsQyrXJnSA';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
